#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.1.0.{build}-{branch}

skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2015

clone_depth: 1

nuget:  
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build_script:
- dotnet --info
- dotnet restore --no-cache
- dotnet build **/project.json --configuration Release --version-suffix %APPVEYOR_BUILD_NUMBER%
- dotnet pack src/RetryMagic/project.json --configuration Release --no-build

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
- dotnet test test/RetryMagic.UnitTests/project.json --configuration Release --no-build

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: src/**/*.nupkg

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off  